version: "3.9"

services:
  backend:
    build:
      context: .
    container_name: aprendendospring_api
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
      JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
    ports:
      - "8080:8080"
